### 1. Understanding the Core Concept Perfectly

Pandas introduces two primary data structures:
•	Series: A 1D array-like object (similar to a single column in Excel).
•	DataFrame: A 2D table-like structure with rows and columns (like a whole Excel sheet).
Key Skills from your Notebooks:
•	Data Loading: Using pd.read_csv() to pull data from local files or even URLs (like the Titanic dataset).
•	Data Exploration: Using .info(), .describe(), and .head() to get a "snapshot" of your data's health (checking for missing values and statistics).
•	Selection & Filtering: Using "Boolean Indexing" to extract specific rows—like finding all Titanic passengers over age 50 or those who paid a fare of 0.
•	Handling Missing Data: Using .isnull(), .fillna(), and .dropna() to clean up the "NaN" (Not a Number) holes in your data.
•	Aggregation: Using .groupby() to calculate averages or counts for different categories (e.g., average age of male vs female passengers).

# 2. Top 1% Best Practice Tasks (The Pune Expert Level)

### Part A: Loading & Inspection (Level 1)

In [2]:
import pandas as pd

E:\Shravani\Softwares\Anaconda\Lib\site-packages\pandas\core\computation\expressions.py:22: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.8.7' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
E:\Shravani\Softwares\Anaconda\Lib\site-packages\pandas\core\arrays\masked.py:56: UserWarning: Pandas requires version '1.4.2' or newer of 'bottleneck' (version '1.3.7' currently installed).
  from pandas.core import (

In [10]:
# 1. Remote Load: Load a dataset directly from a URL (Github) and use .info() to identify which columns have the most missing values.
df = pd.read_csv('https://raw.githubusercontent.com/ine-rmotr-curriculum/FreeCodeCamp-Pandas-Real-Life-Example/refs/heads/master/data/sales_data.csv')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 113036 entries, 0 to 113035
Data columns (total 18 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Date              113036 non-null  str
 1   Day               113036 non-null  int64
 2   Month             113036 non-null  str
 3   Year              113036 non-null  int64
 4   Customer_Age      113036 non-null  int64
 5   Age_Group         113036 non-null  str
 6   Customer_Gender   113036 non-null  str
 7   Country           113036 non-null  str
 8   State             113036 non-null  str
 9   Product_Category  113036 non-null  str
 10  Sub_Category      113036 non-null  str
 11  Product           113036 non-null  str
 12  Order_Quantity    113036 non-null  int64
 13  Unit_Cost         113036 non-null  int64
 14  Unit_Price        113036 non-null  int64
 15  Profit            113036 non-null  int64
 16  Cost              113036 non-null  int64
 17  Revenue           113036 non-null  int64
dtypes: int64(9), str(9)
memory usage: 25.7 MB

In [32]:
# 2. Stat Analysis: Use .describe(include='all') on the Titanic data. What is the most common "Embarked" port?
df = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv")
df.describe(include='all')

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
count,891.000000,891.000000,891.000000,891,891,714.000000,891.000000,891.000000,891,891.000000,204,889
unique,NaN,NaN,NaN,891,2,NaN,NaN,NaN,681,NaN,147,3
top,NaN,NaN,NaN,"Braund, Mr. Owen Harris",male,NaN,NaN,NaN,347082,NaN,G6,S
freq,NaN,NaN,NaN,1,577,NaN,NaN,NaN,7,NaN,4,644
mean,446.000000,0.383838,2.308642,NaN,NaN,29.699118,0.523008,0.381594,NaN,32.204208,NaN,NaN
std,257.353842,0.486592,0.836071,NaN,NaN,14.526497,1.102743,0.806057,NaN,49.693429,NaN,NaN
min,1.000000,0.000000,1.000000,NaN,NaN,0.420000,0.000000,0.000000,NaN,0.000000,NaN,NaN
25%,223.500000,0.000000,2.000000,NaN,NaN,20.125000,0.000000,0.000000,NaN,7.910400,NaN,NaN
50%,446.000000,0.000000,3.000000,NaN,NaN,28.000000,0.000000,0.000000,NaN,14.454200,NaN,NaN
75%,668.500000,1.000000,3.000000,NaN,NaN,38.000000,1.000000,0.000000,NaN,31.000000,NaN,NaN
max,891.000000,1.000000,3.000000,NaN,NaN,80.000000,8.000000,6.000000,NaN,512.329200,NaN,NaN

In [33]:
df = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [17]:
# 3. Memory Check: Compare the memory usage of your DataFrame before and after deleting a column using data.info().
df = pd.read_csv('https://raw.githubusercontent.com/ine-rmotr-curriculum/FreeCodeCamp-Pandas-Real-Life-Example/refs/heads/master/data/sales_data.csv')
print("Before deleting : ")
print(df.info(memory_usage='deep'))
# # setting memory_usage='deep' calculates precise memory usage for text/object columns
df = df.drop('Age_Group', axis = 1)
print("\n\nAfter deleting : ")
print(df.info(memory_usage='deep'))

Before deleting :
<class 'pandas.DataFrame'>
RangeIndex: 113036 entries, 0 to 113035
Data columns (total 18 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Date              113036 non-null  str
 1   Day               113036 non-null  int64
 2   Month             113036 non-null  str
 3   Year              113036 non-null  int64
 4   Customer_Age      113036 non-null  int64
 5   Age_Group         113036 non-null  str
 6   Customer_Gender   113036 non-null  str
 7   Country           113036 non-null  str
 8   State             113036 non-null  str
 9   Product_Category  113036 non-null  str
 10  Sub_Category      113036 non-null  str
 11  Product           113036 non-null  str
 12  Order_Quantity    113036 non-null  int64
 13  Unit_Cost         113036 non-null  int64
 14  Unit_Price        113036 non-null  int64
 15  Profit            113036 non-null  int64
 16  Cost              113036 non-null  int64
 17  Revenue           113036 non-null  int64
dtypes: int64(9), str(9)
memory usage: 25.7 MB
None


After deleting :
<class 'pandas.DataFrame'>
RangeIndex: 113036 entries, 0 to 113035
Data columns (total 17 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Date              113036 non-null  str
 1   Day               113036 non-null  int64
 2   Month             113036 non-null  str
 3   Year              113036 non-null  int64
 4   Customer_Age      113036 non-null  int64
 5   Customer_Gender   113036 non-null  str
 6   Country           113036 non-null  str
 7   State             113036 non-null  str
 8   Product_Category  113036 non-null  str
 9   Sub_Category      113036 non-null  str
 10  Product           113036 non-null  str
 11  Order_Quantity    113036 non-null  int64
 12  Unit_Cost         113036 non-null  int64
 13  Unit_Price        113036 non-null  int64
 14  Profit            113036 non-null  int64
 15  Cost              113036 non-null  int64
 16  Revenue           113036 non-null  int64
dtypes: int64(9), str(8)
memory usage: 23.1 MB
None

In [25]:
# 4. Unique Insights: Find how many unique values exist in the "Pclass" column using .unique() or .nunique().
# .nunique() to get the COUNT of unique values
# .unique() to see the ACTUAL unique values themselves

df = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv")
print("Unique values in PClass")
print("Using .unique : ", df['Pclass'].unique())
print("Using .nunique : ", df['Pclass'].nunique())

Unique values in PClass
Using .unique :  [3 1 2]
Using .nunique :  3

In [30]:
# 5. Exporting: Create a subset of passengers who survived and save it as a new CSV called survivors.csv.
survived_passengers = df[df['Survived'] == 1]
survived_passengers.to_csv("survivors.csv", index=False)
print("Saved survivors.csv file")

Saved survivors.csv file

### Part B: Filtering & Selection (Level 2)

In [36]:
# 6. Complex Filter: Extract passengers who were in 1st Class AND were Female.
df[(df['Pclass'] == 1) & (df['Sex'] == 'female')]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
52,53,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.0,1,0,PC 17572,76.7292,D33,C
...,...,...,...,...,...,...,...,...,...,...,...,...
856,857,1,1,"Wick, Mrs. George Dennick (Mary Hitchcock)",female,45.0,1,1,36928,164.8667,NaN,S
862,863,1,1,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",female,48.0,0,0,17466,25.9292,D17,S
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S

In [39]:
# 7. Fare Outliers: Find passengers who paid a fare in the top 5% of all ticket prices.
df['Fare'].max()

df[df['Fare'] == 512.3292]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
258,259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,NaN,C
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,C
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C

In [45]:
# 8. Column Operations: Create a new column called "Is_Adult" which is True if Age $\ge$ 18 and False otherwise.
df['Is_Adult'] = df['Age'] >= 18
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Is_Adult
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,True
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,True
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,True
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,True
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,True

In [46]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Is_Adult
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S,True
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S,True
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S,False
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C,True
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q,True

In [52]:
# 9. String Search: Filter the "Name" column to find all passengers with the title "Master" (common in NLP text filtering).
df[(df['Name'].str.contains('Master', na=False))]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Is_Adult
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.00,3,1,349909,21.0750,NaN,S,False
16,17,0,3,"Rice, Master. Eugene",male,2.00,4,1,382652,29.1250,NaN,Q,False
50,51,0,3,"Panula, Master. Juha Niilo",male,7.00,4,1,3101295,39.6875,NaN,S,False
59,60,0,3,"Goodwin, Master. William Frederick",male,11.00,5,2,CA 2144,46.9000,NaN,S,False
63,64,0,3,"Skoog, Master. Harald",male,4.00,3,2,347088,27.9000,NaN,S,False
65,66,1,3,"Moubarek, Master. Gerios",male,NaN,1,1,2661,15.2458,NaN,C,False
78,79,1,2,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,29.0000,NaN,S,False
125,126,1,3,"Nicola-Yarred, Master. Elias",male,12.00,1,0,2651,11.2417,NaN,C,False
159,160,0,3,"Sage, Master. Thomas Henry",male,NaN,8,2,CA. 2343,69.5500,NaN,S,False
164,165,0,3,"Panula, Master. Eino Viljami",male,1.00,4,1,3101295,39.6875,NaN,S,False
165,166,1,3,"Goldsmith, Master. Frank John William ""Frankie""",male,9.00,0,2,363291,20.5250,NaN,S,False
171,172,0,3,"Rice, Master. Arthur",male,4.00,4,1,382652,29.1250,NaN,Q,False
176,177,0,3,"Lefebre, Master. Henry Forbes",male,NaN,3,1,4133,25.4667,NaN,S,False
182,183,0,3,"Asplund, Master. Clarence Gustaf Hugo",male,9.00,4,2,347077,31.3875,NaN,S,False
183,184,1,2,"Becker, Master. Richard F",male,1.00,2,1,230136,39.0000,F4,S,False
193,194,1,2,"Navratil, Master. Michel M",male,3.00,1,1,230080,26.0000,F2,S,False
261,262,1,3,"Asplund, Master. Edvin Rojj Felix",male,3.00,4,2,347077,31.3875,NaN,S,False
278,279,0,3,"Rice, Master. Eric",male,7.00,4,1,382652,29.1250,NaN,Q,False
305,306,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S,False
340,341,1,2,"Navratil, Master. Edmond Roger",male,2.00,1,1,230080,26.0000,F2,S,False
348,349,1,3,"Coutts, Master. William Loch ""William""",male,3.00,1,1,C.A. 37671,15.9000,NaN,S,False
386,387,0,3,"Goodwin, Master. Sidney Leonard",male,1.00,5,2,CA 2144,46.9000,NaN,S,False
407,408,1,2,"Richards, Master. William Rowe",male,3.00,1,1,29106,18.7500,NaN,S,False
445,446,1,1,"Dodge, Master. Washington",male,4.00,0,2,33638,81.8583,A34,S,False
480,481,0,3,"Goodwin, Master. Harold Victor",male,9.00,5,2,CA 2144,46.9000,NaN,S,False
489,490,1,3,"Coutts, Master. Eden Leslie ""Neville""",male,9.00,1,1,C.A. 37671,15.9000,NaN,S,False
549,550,1,2,"Davies, Master. John Morgan Jr",male,8.00,1,1,C.A. 33112,36.7500,NaN,S,False
709,710,1,3,"Moubarek, Master. Halim Gonios (""William George"")",male,NaN,1,1,2661,15.2458,NaN,C,False
751,752,1,3,"Moor, Master. Meier",male,6.00,0,1,392096,12.4750,E121,S,False
755,756,1,2,"Hamalainen, Master. Viljo",male,0.67,1,1,250649,14.5000,NaN,S,False
787,788,0,3,"Rice, Master. George Hugh",male,8.00,4,1,382652,29.1250,NaN,Q,False
788,789,1,3,"Dean, Master. Bertram Vere",male,1.00,1,2,C.A. 2315,20.5750,NaN,S,False
802,803,1,1,"Carter, Master. William Thornton II",male,11.00,1,2,113760,120.0000,B96 B98,S,False
803,804,1,3,"Thomas, Master. Assad Alexander",male,0.42,0,1,2625,8.5167,NaN,C,False
819,820,0,3,"Skoog, Master. Karl Thorsten",male,10.00,3,2,347088,27.9000,NaN,S,False
824,825,0,3,"Panula, Master. Urho Abraham",male,2.00,4,1,3101295,39.6875,NaN,S,False
827,828,1,2,"Mallet, Master. Andre",male,1.00,0,2,S.C./PARIS 2079,37.0042,NaN,C,False
831,832,1,2,"Richards, Master. George Sibley",male,0.83,1,1,29106,18.7500,NaN,S,False
850,851,0,3,"Andersson, Master. Sigvard Harald Elias",male,4.00,4,2,347082,31.2750,NaN,S,False
869,870,1,3,"Johnson, Master. Harold Theodor",male,4.00,1,1,347742,11.1333,NaN,S,False

In [59]:
# 10. Index Reset: Slice the first 10 rows and then use .reset_index(drop=True) to make the index start from 0 again.
index = df[:10]
index = index.reset_index(drop=True)
index.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Is_Adult
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,True
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,True
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,True
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,True
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,True

### Part C: Cleaning & Transformation (Level 3)

In [61]:
# 11. Smart Fill: Fill the missing "Age" values not with a single number, but with the median age of the entire dataset.
df['Age'].median()

28.0

In [65]:
df['Age'] = df['Age'].fillna(df['Age'].median())
print(df['Age'].isna().sum())

0

In [74]:
# 12. Categorical Swap: Change "male" to 1 and "female" to 0 in the "Sex" column using .map() or .replace().
def gender(x):
    if x == 'male':
        return 1
    else:
        return 0

df['New_Age'] = df['Sex'].apply(gender)
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Is_Adult,New_Age
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,True,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,True,0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,True,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,True,0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,True,1

In [77]:
# 13. Null Drop: Drop all rows where "Cabin" is missing. How many rows are left?
new_Cabin = df.dropna(subset="Cabin")
new_Cabin

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Is_Adult,New_Age
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,True,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,True,0
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,True,1
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S,False,0
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S,True,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S,True,0
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S,True,1
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C,True,0
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,True,0
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,True,1

In [78]:
print(len(new_Cabin))

204

In [81]:
# 14. Sorting: Sort the DataFrame by "Fare" (highest first) and then by "Age" (youngest first).
multisort = df.sort_values(by = ["Fare", "Age"], ascending = [False, True])
print(multisort[["Name", "Age", "Fare"]].head())

                                   Name   Age      Fare
258                    Ward, Miss. Anna  35.0  512.3292
737              Lesurer, Mr. Gustave J  35.0  512.3292
679  Cardeza, Mr. Thomas Drake Martinez  36.0  512.3292
27       Fortune, Mr. Charles Alexander  19.0  263.0000
88           Fortune, Miss. Mabel Helen  23.0  263.0000

In [82]:
# 15. NLP Text Cleaning: In the "Name" column, remove all punctuation marks using .str.replace() and a regex.
df["Name"].str.replace(',', "")

0                                 Braund Mr. Owen Harris
1      Cumings Mrs. John Bradley (Florence Briggs Tha...
2                                  Heikkinen Miss. Laina
3            Futrelle Mrs. Jacques Heath (Lily May Peel)
4                                Allen Mr. William Henry
                             ...
886                                 Montvila Rev. Juozas
887                          Graham Miss. Margaret Edith
888              Johnston Miss. Catherine Helen "Carrie"
889                                 Behr Mr. Karl Howell
890                                   Dooley Mr. Patrick
Name: Name, Length: 891, dtype: str

In [88]:
df['Name'] = df['Name'].str.replace(r'[^\w\s]','')
df['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: str

### Part D: Expert Aggregations (Level 4)

In [105]:
# 16. Group Analysis: Group the data by "Pclass" and calculate the mean fare for each class.
df = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv")
group = df.groupby('Pclass')['Fare'].mean()
group

Pclass
1    84.154687
2    20.662183
3    13.675550
Name: Fare, dtype: float64

In [106]:
# 17. Survival Rates: Use .groupby() to find the percentage of people who survived in each "Sex" category
# The groupby() function in pandas is used to split a dataset into groups based on one or more category columns, apply a calculation to each group, 
# and combine the results into a new summary table.
# syntax
# df.groupby(by='Group_Column')['Calculation_Column'].aggregation_function()

df.groupby('Sex')['Survived'].mean() * 100

Sex
female    74.203822
male      18.890815
Name: Survived, dtype: float64

In [ ]:
# 18. Pivot Tables: Research .pivot_table(). Create a table showing the number of survivors, broken down by both "Pclass" and "Sex".

In [91]:
# 19. Merging: Create two DataFrames (one with names and IDs, another with IDs and Marks) and use pd.merge() to combine them.
data1 = {
    'Name' : ['Alice', 'George', 'Bob', 'John', 'Sia'],
    'ID' : [101, 102, 103, 104, 105]
}
df1 = pd.DataFrame(data1)

data2 = {
    'ID' : [101, 102, 103, 104, 105],
    'Marks' : [95, 96, 85, 45, 68]
}
df2 = pd.DataFrame(data2)

merged_dataset = pd.merge(df1, df2)
merged_dataset

     Name   ID  Marks
0   Alice  101     95
1  George  102     96
2     Bob  103     85
3    John  104     45
4     Sia  105     68

In [4]:
# 20. Time Series (Preview): If a column has dates, convert it to datetime format using pd.to_datetime() and extract the "Month".
df = pd.read_csv('C:/Users/shrav/Downloads/Electric_Production.csv')
df

          DATE  IPG2211A2N
0     1/1/1985     72.5052
1     2/1/1985     70.6720
2     3/1/1985     62.4502
3     4/1/1985     57.4714
4     5/1/1985     55.3151
..         ...         ...
392   9/1/2017     98.6154
393  10/1/2017     93.6137
394  11/1/2017     97.3359
395  12/1/2017    114.7212
396   1/1/2018    129.4048

[397 rows x 2 columns]

In [6]:
df['DATE'] = pd.to_datetime(df['DATE'])
df['Month'] = df['DATE'].dt.month
df.head()

        DATE  IPG2211A2N  Month
0 1985-01-01     72.5052      1
1 1985-02-01     70.6720      2
2 1985-03-01     62.4502      3
3 1985-04-01     57.4714      4
4 1985-05-01     55.3151      5